### ISSUE TITLE
Cannot find a provider for swap_file[...] on ubuntu version 14.04

### ISSUE THREAD

**Issue by jonathanhoskin** [sethvargo-cookbooks/swap#22]
In my recipe:

    swap_file '/var/swapfile' do
      size 1024    # MBs
      persist true
      not_if { system("swapon -s | grep -v ^Filename | grep -v '/var/swapfile'") }
    end

Getting this error during a converge of a new server with Chef client v12.4.0:

    * swap_file[/var/swapfile] action create
      
      ================================================================================
      Error executing action `create` on resource 'swap_file[/var/swapfile]'
      ================================================================================
      
      ArgumentError
      -------------
      Cannot find a provider for swap_file[/var/swapfile] on ubuntu version 14.04
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/my_cookbook/recipes/swap.rb
      
        1: swap_file '/var/swapfile' do
        2:   size 1024    # MBs
        3:   persist true
        4:   not_if { system("swapon -s | grep -v ^Filename | grep -v '/var/swapfile'") }
        5: end
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/my_cookbook/recipes/swap.rb:1:in `from_file'
      
      swap_file("/var/swapfile") do
        action :create
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :swap_file
        cookbook_name "my_cookbook"
        recipe_name "swap"
        size 1024
        persist true
        not_if { #code block }
      end

Is this related to the breaking changes that are in Chef client v12.4.0? We have had other issues today since it's release.

**Comment by olbrich** [comment]
The 'swap_tuning' cookbook also fails with this error.

**Comment by olbrich** [comment]
Everything works fine when using chef 12.3.0

**Comment by sethvargo** [comment]
@danielsdeleo @jkeiser any ideas here?

**Comment by jonathanhoskin** [comment]
Just an FYI. We have pinned our Chef client back to 12.2.1 for now and it converged ok.

**Comment by danielsdeleo** [comment]
I haven't been following the resource changes closely enough to know off-hand. I'll try to track down John in chat.

**Comment by jkeiser** [comment]
It's almost certainly those changes related.  Not sure what yet, looking.

**Comment by sethvargo** [comment]
Thanks!

**Comment by jkeiser** [comment]
@jdmundrawala tracked this down: it happens when you have the combo of an LWRP resource, and a provider in Chef::Provider that uses automatic name (doesn't declare `provides`).  He's working on a fix right now, but if you want to get past it today, you can add `provides :swap_file` to the provider class and things will be right as rain.

Sorry for the inconvenience!

**Comment by sethvargo** [comment]
@jkeiser is that backwards compatible with Chef 11?

**Comment by acondrat** [comment]
Hello and thanks for the fix! Is there a plan to bump and release swap cookbook to include this fix?

**Comment by jonathanhoskin** [comment]
Yes, will there be a release soon?
